### ISSUE TITLE
spkl: can't connect

### ISSUE THREAD

**Issue by devkeydet** [scottdurow/SparkleXrm#160]
REPRO:

deploy-plugins.bat

Using 'C:\[path details removed]\packages\spkl.1.0.43.1\tools\spkl.exe'
spkl Task Runner v1.0.43.1      Tasks v1.0.43.1
Enter a CRM server name and port [crm.dynamics.com]: crm.dynamics.com
Is this organization provisioned in Microsoft Office 365 (y/n) [y]: y
The application terminated with an error.
The authentication endpoint Kerberos was not found on the configured Secure Token Service!
   at Microsoft.Xrm.Sdk.Client.IssuerEndpointDictionary.GetIssuerEndpoint(TokenServiceCredentialType credentialType)
   at Microsoft.Xrm.Sdk.Client.AuthenticationCredentials.get_IssuerEndpoint()
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateWithADFSForOrgId(AuthenticationCredentials authenticationCredentials, Uri identifier)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceConfiguration.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetProxy[TService,TProxy](Configuration currentConfig)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetDiscoveryProxy()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetOrganizationAddress()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration()
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)

**Comment by scottdurow** [comment]
Hey Marc,
Perhaps this is something like - https://www.magnetismsolutions.com/blog/roshanmehta/2013/09/20/the-authentication-endpoint-kerberos-was-not-found-on-the-configured-secure-token-service

Can you connect using the Connection Tester in the SDK (SDK\Bin\LoginControlTester.exe)
Also - can you run the SDK sample code using the HelperCode?

**Comment by devkeydet** [comment]
I can if I "Show Advanced" and select "North America" explicitly.  However, if I allow discovery, I get an error when it tries to log in to "CRM Online - Germany".  Note that the following works just fine:

spkl plugins "some_valid_conn_string"

I can probably carve out some time next week to clone/fork/debug/fix if the root cause isn't obvious to you.  This would be my first time looking at spkl source so I'd need some time to get acquainted.  BTW, spkl is *awesome*.  Love that I can use it from both VS & VSCode.

**Comment by scottdurow** [comment]
When you pass a connection string spkl uses the XrmTooling - otherwise, it uses the SDK helper connection code - so maybe there is an issue with that.

**Comment by BogdanPushtiu** [comment]
Hi Scott, I'm having the same issue trying to connect to a D365 instance. This is what I'm getting:

spkl Task Runner v1.0.87.1      Tasks v1.0.87.1
Enter a CRM server name and port [crm.dynamics.com]: ABC.crm
amics.com
Is this organization provisioned in Microsoft Office 365 (y/n) [y]: y
The application terminated with an error.
Metadata contains a reference that cannot be resolved: 'https://disco.onea
dcrmdev.crm11.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetri
etrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(R
CallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(M
aRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(U
ress, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpo
adata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri
ean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagemen
vice](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagemen
vice](Uri serviceUri)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetProxy[TService,TProxy]
guration currentConfig)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetDiscoveryProxy()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetOrganizationAddress()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration()
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
The remote server returned an error: (503) Server Unavailable.
Press any key to continue . . .

Do you have any thoughts please? I can connect using the LoginControlTester from the latest D365 SDK.

Thank you!

**Comment by scottdurow** [comment]
@devkeydet Did you manage to find the issue with this? Perhaps we need to re-write the console login code to use XrmTooling?

**Comment by devkeydet** [comment]
Nope.  I am still having the issue.  My workaround is to pass spkl a connection string, but looking forward to not having to do that:).

**Comment by scottdurow** [comment]
Right - I use that technique in all my CI builds from VSTS. Need to get this resolved so I think I'll just re-write the console login code!

**Comment by devkeydet** [comment]
Any updates on when you think you might get to this?

**Comment by carltoncolter** [comment]
Hey... if you're not working on this already I'm willing to take a crack at making it use the new XrmTooling to connect.

I'm running into the same problem.

**Comment by scottdurow** [comment]
Not started it yet - but it's on my list.
@carltoncolter A PR would be great! 👍

**Comment by ayantorcasitas** [comment]
Got this issue:

The application terminated with an error.
Timestamp: 3/4/2024 2:42:36 PM
Code: -2147160034
Message: Invalid number of components in version. Version: Data

Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Update(Entity entity)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterAssembly(FileInfo assemblyFilePath, Assembly assembly, IEnumerable`1 pluginTypes, Boolean isWorkflowActivity)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterPlugin(String file, Boolean excludePluginSteps)
   at SparkleXrm.Tasks.DeployPluginsTask.DeployPlugins(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.DeployPluginsTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Plugin Trace:
[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.TargetAttributeValidationPlugin]
[fc743e7d-fbea-4695-bdb9-7d78334c8474: TargetAttributeValidationPlugin]


Inner Fault: Has Inner Fault
