### ISSUE TITLE
Unable to Unpack 2015 Solution

### ISSUE THREAD

**Issue by namurdock** [scottdurow/SparkleXrm#201]
I am receiving the following error when running the unpack command in spkl task runner.

```
The application terminated with an error.
Timestamp: 14/02/2018 11:49:47
Code: -2147220715
Message: Unrecognized request parameter: ExportExternalApplications

Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.Execute(OrganizationRequest request)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPackSolution(SolutionPackageConfig solutionPackagerConfig, String targetFolder)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPack(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.SolutionPackagerTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Inner Fault: Has Inner Fault
```

After a little research on the net i have found this in relation to the Xrm-Ci-Framework from Wael Hamze.  (https://github.com/WaelHamze/xrm-ci-framework/issues/6).

Pulling webresources worked fine, so I am hoping i can overcome this issue, otherwise  I can revert to using the xrm-ci-framework for 2015 which will unpack for me.

**Comment by scottdurow** [comment]
Looks like it's a backward compatibility issue in the latest SDK tools.
Can you try Install-Package spkl -Version 1.0.178.1

**Comment by namurdock** [comment]
Thanks Scott, I was hoping you were going to say something like that... 

 I get the same error running 1.0.178.1

```
spkl Task Runner v1.0.178.1     Tasks v1.0.178.1

(0) Add New Server Config

Unpacking solution
Searching for packager config in 'C:\Users\xxx\Documents\Repos\xxx'
Using Config 'C:\Users\xxx\Documents\Repos\xxx'
The application terminated with an error.
Timestamp: 14/02/2018 13:57:57
Code: -2147220715
Message: Unrecognized request parameter: ExportExternalApplications

Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.Execute(OrganizationRequest request)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPackSolution(SolutionPackageConfig solutionPackagerConfig, String targetFolder)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPack(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.SolutionPackagerTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Inner Fault: Has Inner Fault
Press any key to continue . . .guration (Maximum number up to 9)


```

**Comment by scottdurow** [comment]
You could always try overwriting the solution packager in the packages folder with the 2015 version.

**Comment by namurdock** [comment]
Checking the packages folder i don't have a solutionPackager.exe file in there. The only place i find it is in the bin\CoreTools folder created by the nupkg install. Overriding this seems to have no effect.

**Comment by namurdock** [comment]
If it helps... I am not sure it is the up packing causing the issue but actually the Export of the solution.

**Comment by scottdurow** [comment]
I've experienced a similar issue - I've had to overwrite the core tools with the versions from the nuget package - https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools/8.0.0

**Comment by namurdock** [comment]
Thanks Scott, I've hit another hurdle in the world of VSTS, but you can close this issue off.
