### ISSUE TITLE
pack+import bat - solution import issue

### ISSUE THREAD

**Issue by abz789** [scottdurow/SparkleXrm#210]
getting error when running pack+import.bat command using spkl in VS2017 
any idea?

Following root components are not defined in customizations:
  Type='PluginAssembly', Id (or schema name)='{0201327f-2822-e811-a8a4-0022480173bb}'.

Following objects, required by the solution, are not present. /n/r  Type='PluginAssembly', Id (or schema name)='PluginAssembly-SF365Plugins, Version=2.0.0.0, Culture=neutral, PublicKeyToken=15f92f8a08de05d5'.
/n/r Please do a dependency check on your solution prior to exporting, add the missing objects to your solution and re-export/n/r
Error occurred during execution of plugin 'RootComponentValidation': RootComponent validation failed.
See log file 'packagerlog.txt' for details.
CrmSvcUtil Runtime = 00:00:01.4195902
Solution Packager exited with error 3

**Comment by abz789** [comment]
2018-03-07 18:33:19.295 - Info	Processing Component: Entities
2018-03-07 18:33:19.298 - Info	Processing Component: Roles
2018-03-07 18:33:19.340 - Info	Processing Component: Workflows
2018-03-07 18:33:19.346 - Info	Processing Component: FieldSecurityProfiles
2018-03-07 18:33:19.347 - Info	Processing Component: Templates
2018-03-07 18:33:19.349 - Info	Processing Component: EntityMaps
2018-03-07 18:33:19.349 - Info	Processing Component: EntityRelationships
2018-03-07 18:33:19.351 - Verbose	Reading: C:\SF365\Solution\package\Other\Relationships.xml
2018-03-07 18:33:19.354 - Info	Processing Component: optionsets
2018-03-07 18:33:19.354 - Info	Processing Component: SolutionPluginAssemblies
2018-03-07 18:33:19.372 - Verbose	Reading: C:\SF365\Solution\package\PluginAssemblies\SF365Plugins-0201327F-2822-E811-A8A4-0022480173BB\SF365Plugins.dll.data.xml
2018-03-07 18:33:19.379 - Info	 - SF365Plugins, Version=2.0.0.0, Culture=neutral, PublicKeyToken=15f92f8a08de05d5
2018-03-07 18:33:19.382 - Info	Mapping: C:\SF365\Solution\package\PluginAssemblies\SF365Plugins-0201327F-2822-E811-A8A4-0022480173BB\SF365Plugins.dll to C:\SF365\Plugins\bin\Debug\SF365Plugins.dll
2018-03-07 18:33:19.383 - Verbose	Reading: C:\SF365\Plugins\bin\Debug\SF365Plugins.dll
2018-03-07 18:33:19.384 - Info	Processing Component: SdkMessageProcessingSteps
2018-03-07 18:33:19.387 - Verbose	Reading: C:\SF365\Solution\package\SdkMessageProcessingSteps\{703b4e82-2822-e811-a8a4-00224801a0fe}.xml
2018-03-07 18:33:19.407 - Warning	Following root components are not defined in customizations:
  Type='PluginAssembly', Id (or schema name)='{0201327f-2822-e811-a8a4-0022480173bb}'.

2018-03-07 18:33:19.407 - Warning	Following root components are not defined in customizations:
  Type='PluginAssembly', Id (or schema name)='{0201327f-2822-e811-a8a4-0022480173bb}'.

2018-03-07 18:33:19.409 - Error	Following objects, required by the solution, are not present. /n/r  Type='PluginAssembly', Id (or schema name)='PluginAssembly-SF365Plugins, Version=2.0.0.0, Culture=neutral, PublicKeyToken=15f92f8a08de05d5'.
/n/r Please do a dependency check on your solution prior to exporting, add the missing objects to your solution and re-export/n/r
2018-03-07 18:33:19.415 - Error	Error occurred during execution of plugin 'RootComponentValidation': RootComponent validation failed.
2018-03-07 18:33:19.416 - Error	See log file 'packagerlog.txt' for details.
2018-03-07 18:33:19.527 - Error	Microsoft.Crm.Tools.SolutionPackager.PluginExecutionException: RootComponent validation failed.
   at Microsoft.Crm.Tools.SolutionPackager.Plugins.RootComponentsValidation.BeforeWrite(PluginContext pluginContext)
   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.InvokePlugin(PluginConfigurationElement pluginConfig, Action`1 action)
   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.Run(IPackageReader reader, IPackageWriter writer)
   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.Run()
   at Microsoft.Crm.Tools.SolutionPackager.Program.Main(String[] args)
2018-03-07 18:33:19.530 - Verbose	CrmSvcUtil Runtime = 00:00:01.4195902

**Comment by abz789** [comment]
fixed it by installing latest nuget pkg
