### ISSUE TITLE
The application terminated with error. Root element is missing. 

### ISSUE THREAD

**Issue by ssskumar19** [scottdurow/SparkleXrm#268]
Hi, I am trying to setup spkl but while executing the  deployment deploy-plugins.bat, getting below error. Did i missed something here? 

**Error is**
Using 'C:\Users\qxw3094\source\repos\Demo.Plugins\packages\spkl.1.0.198\tools\spkl.exe'
spkl Task Runner v1.0.198.1     Tasks v1.0.198.1
The application terminated with an error.
Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.ReadConfigurations()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration(Boolean ignoreLocalPrincipal)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Press any key to continue . . .

Thanks

**Comment by scottdurow** [comment]
It looks like it is trying to read the connections file but it is corrupt. Can you try deleting the file at C:\Users\<Your User>\AppData\Roaming\CrmServer\Credentials.xml
