### ISSUE TITLE
Unexpected error after cloning repo: Code -2147220970

### ISSUE THREAD

**Issue by AlanJudi** [scottdurow/SparkleXrm#272]
Hello Scott. I recently switched computers and had to clone my repo onto a new computer. Everything works fine, I get no build errors or warnings, however, when I go to run SPKL deploy plugins.bat, I get the following error:

```
5 plugin(s) found!
Registering Plugin 'Plugins' from 'C:\Users\khali\Source\Repos\DCWIMS_\Plugins\bin\Debug\Plugins.dll'
The application terminated with an error.
Timestamp: 2018-09-14 5:34:27 PM
Code: -2147220970
Message: An unexpected error occurred.

Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Create(Entity entity)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.CreateCore(Entity entity)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.Create(Entity entity)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterAssembly(FileInfo assemblyFilePath, Assembly assembly, IEnumerable`1 pluginTypes)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterPlugin(String file)
   at SparkleXrm.Tasks.DeployPluginsTask.DeployPlugins(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.DeployPluginsTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Inner Fault: Has Inner Fault
Press any key to continue . . .
```

I get error Code: -2147220970. Have no idea what that means.. If anyone could guide me on how I could gain back access to spkl as I need it for continuous integration!

Thanks in advance!

**Comment by scottdurow** [comment]
Not much to go on in the error details - did you get anywhere with this?

**Comment by AlanJudi** [comment]
I switched to .Net framework 4.5 and magically it worked! Even though I was previously using 4.7 without issues.
