### ISSUE TITLE
Unable to connect to crm online using  spkl.1.0.226

### ISSUE THREAD

**Issue by simba22042** [scottdurow/SparkleXrm#279]
I am trying to run download-webresources.bat but keep getting the following 

spkl Task Runner v1.0.226.1     Tasks v1.0.226.1
Enter a CRM server name and port [crm.dynamics.com]: XXXXXX.crm.dynamics.com
Is this organization provisioned in Microsoft Office 365 (y/n) [y]: y
The application terminated with an error.
Metadata contains a reference that cannot be resolved: 'https://disco.XXXXXX.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetProxy[TService,TProxy](Configuration currentConfig)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetDiscoveryProxy()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetOrganizationAddress()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration(Boolean ignoreLocalPrincipal)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Unable to connect to the remote server
Press any key to continue . . .

**Comment by mattp65** [comment]
Don’t include the Orgname in the url:

Enter a CRM server name and port [crm.dynamics.com]: crm.dynamics.com

 

Once you authenticate, it will then display a list of matching orgs.

**Comment by simba22042** [comment]
Hi Matt,

That worked. Sorry for my ignorance on spkl just getting started on this. Now I am getting the following 

**Solution section not found in spkl.json. This is needed to determine where to store the webresources!
Press any key to continue . . .**

Here is the spkl.json file.

```
{

    "webresources": [
      {
        /* 
            Option - profile - Provide a comma delimitered list of profile names that can be referenced when calling spkl
            */
        "profile": "default,debug",

        /*
            Optional - root - Provide the relatative path of the webresources.
            */
        "root": "",
        "solution": "ControlSystems",

        /*
            Optional - solution - Add webresources to a solution when deploying
             
               "solution": "",

        /*
            Required - files - List the webresources to deploy relatative to the root of this file (or the the root parameter above)
            */
        "files": [
          {
            "uniquename": "new_/js/somefile.js",
            "file": "new_\\js\\somefile.js",
            "description": ""
          }
        ]
      }
    ]
   
    
} 
```
```

**Comment by scottdurow** [comment]
You will need to add a solutions section as described by https://github.com/scottdurow/SparkleXrm/wiki/spkl#solution-packager 
This will define the location to store the webresources that are downloaded.

**Comment by flashybyte** [comment]
I am unable to connect to CRM using the tool . if i give crm.dynamics.com its throwing as invalid input , if i give the org.crm.dynamics.com its not returning anything no log as well

**Comment by flashybyte** [comment]
i was able to connect once i clear the token cache thanks
