### ISSUE TITLE
EarlyBound Generator failing

### ISSUE THREAD

**Issue by bennyboy23** [scottdurow/SparkleXrm#326]
Hi, when attempting to use the earlybound generator with spkl, I receive the below error
> Loading config from 'D:\Work\Repositories\Fabric\packages\Microsoft.CrmSdk.CoreTools.9.0.3.4\content\bin\coretools\spkl.crmsvcutil.config'
19:57:46	CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.InvalidOperationException: Unable to initialize the native configuration support external to the web worker process (HRESULT=0x80040154).
19:57:46	nativerd.dll must be in %windir%\system32\inetsrv.
19:57:46	   at System.Web.Configuration.ProcessHostConfigUtils.NativeConfigWrapper..ctor()
19:57:46	   at System.Web.Configuration.ProcessHostConfigUtils.InitStandaloneConfig()
19:57:46	   at System.Web.Configuration.ProcessHostMapPath..ctor(IProcessHostSupportFunctions functions)
19:57:46	   at System.Web.Configuration.IISMapPath.GetInstance()
19:57:46	   at System.Web.Configuration.WebConfigurationHost.ChooseAndInitConfigMapPath(Boolean useConfigMapPath, IConfigMapPath configMapPath, ConfigurationFileMap fileMap)
19:57:46	   at System.Web.Configuration.WebConfigurationHost.InitForConfiguration(String& locationSubPath, String& configPath, String& locationConfigPath, IInternalConfigRoot configRoot, Object[] hostInitConfigurationParams)

this is the spkl file
[spkl.txt](https://github.com/scottdurow/SparkleXrm/files/3267279/spkl.txt)
the database version is 9.1.0.5228
I have updated the coretools to the latest version and no change.

Any advice would be most welcome

**Comment by bennyboy23** [comment]
I am able to unpack my solution, which to me indicates either a problem with svcutil or my spkl file

**Comment by bennyboy23** [comment]
This was solved by installing a windows feature that was deactivated in a recent windows update.
The solution s found here https://github.com/MscrmTools/XrmToolBox/issues/778
