### ISSUE TITLE
Cannot use  spkl get-webresources

### ISSUE THREAD

**Issue by aboodh95** [scottdurow/SparkleXrm#365]
Hi,

I'm trying to use the command  spkl get-webresources /s:ets where ets is my solution prefix, but I'm getting the error 

`The application terminated with an error.
An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at SparkleXrm.Tasks.DownloadWebresourceConfigTask.ExecuteInternal(String filePath, OrganizationServiceContext ctx)      at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)`

**Comment by aboodh95** [comment]
any update

**Comment by scottdurow** [comment]
@aboodh95 This looks like you have some duplicate webresource names (excluding the prefix). There is a match list that is created to try and locate the local webresource by the file path (https://github.com/scottdurow/SparkleXrm/blob/spkl_dev/spkl/SparkleXrm.Tasks/Tasks/DownloadWebresourceConfigTask.cs#L80) - if there are multiple paths that are the same then it will try and add duplicates. I guess we will need to filter this to only get the webresources using the specified prefix

**Comment by aboodh95** [comment]
okay, I will try to find if I do have a web resource that shares the same path (without prefix) with other solution

**Comment by aboodh95** [comment]
@scottdurow, for example, I found some,
![image](https://user-images.githubusercontent.com/12459798/78451987-bceddb00-7699-11ea-8c06-b96f6a150c9f.png)
yo can see, as you say all the files have the same path except for the extension
