### ISSUE TITLE
cannot connect to v9.1

### ISSUE THREAD

**Issue by dvdbeahm** [scottdurow/SparkleXrm#370]
I am trying to deploy web resources w/ spkl but the URL is not working with v9.1 online; getting the error below.

Looks like there needs to be a way to set: config.DiscoveryUri = new Uri(String.Format("https://disco.{0}/XRMServices/api/discovery/v9.1/Discovery.svc", config.ServerAddress));

Not able to go much further as the BuildTasks project is not supported in my VS2019 setup.

**Error Message**:
Is this organization provisioned in Microsoft Office 365 (y/n) [y]: y
The application terminated with an error.
Metadata contains a reference that cannot be resolved: 'https://disco._solutionname_.crm.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetProxy[TService,TProxy](Configuration currentConfig)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetDiscoveryProxy()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetOrganizationAddress()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration(Boolean ignoreLocalPrincipal)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
The remote name could not be resolved: 'disco._solutionname_.crm.dynamics.com'
Error Code=1

**Comment by vivekkk4** [comment]
I am also getting the same error.

**Comment by scottdurow** [comment]
Could you try using https://www.nuget.org/packages/spkl/1.0.394-beta 
This now uses the Xrm.Tooling for the interactive login at the command line

**Comment by vivekkk4** [comment]
Thanks Scott, this release has fixed the issue.

**Comment by dvdbeahm** [comment]
Works great - thanks!
