### ISSUE TITLE
The underlying connection was closed: The connection was closed unexpectedly. Error Code=1.

### ISSUE THREAD

**Issue by heosua** [scottdurow/SparkleXrm#421]
Hi, 

Hope someone could help. 

I'm using spkl Task Runner v1.0.440.1 & is trying to run the unpack.bat but getting the error below. Not sure why there is a connection issue as i can run deploy-plugins.bat , deploy-webresources.bat, download--webresources.bat .. etc to the same solution successfully using the same saved server connection. Any help is much appreciated. Thanks.

**Unpacking solution
Searching for packager config in 'C:\CRMDev\CRMTest\CRMTestSolution\Webresources\spkl\..'
Using Config 'C:\CRMDev\CRMTest\CRMTestSolution\Webresources'
The application terminated with an error.
The underlying connection was closed: The connection was closed unexpectedly.

Server stack trace:
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Execute(OrganizationRequest request)
   at SparkleXrm.Tasks.SolutionPackagerTask.ExportUnmanagedSolution(SolutionPackageConfig config, String filePath)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPackSolution(SolutionPackageConfig solutionPackagerConfig, String targetFolder)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPack(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.SolutionPackagerTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
The underlying connection was closed: The connection was closed unexpectedly.**

Below is the spkl.json

{
    
    /*
    The solutions section defines a solution that can be extracted to individual xml files to make
    versioning of Dynamics metadata (entities, attributes etc) easier
    */
    "solutions": [
      {
        "profile": "default,debug",
        /*
            The unique name of the solution to extract, unpack, pack and import
            */
        "solution_uniquename": "MyTestSolution",
        /*
            The relative folder path to store the extracted solution metadata xml files
            */
        "packagepath": "package",
        /*
            The relative path name of the solution to pack into
            */
        "solutionpath": "solution_{0}_{1}_{2}_{3}.zip",
        /*
            Set to 'unmanaged', 'managed', 'both_unmanaged_import' or 'both_managed_import' - default to 'unmanaged' if omitted
            */
        "packagetype": "unmanaged",
        /*
            Set to 'true' to increment the minor version number before importing from the xml files
            */
        "increment_on_import": false
      }
    ]
}

**Comment by heosua** [comment]
Thanks for replying Scott. 

I've ran this multiple times with same error. Have also tried on multiple solutions/projects but no luck. I'll create a new CRM solution and try to see. Thank you.

**Comment by mariokrajmer** [comment]
I have the similar issue. 
It seems that it is just stuck or something. I am not getting any error, but the spkl unpack just waits forever (mostly on cold start - when i haven't run the unpack for a few hours). Normally the unpack takes ~6 minutes. But when running during night from Azure Devops pipeline, the tasks timeout (set for 60 minutes) cuts off the execution. Usually when i rerun it manually it works (most of the times). 
Does anybody know what could be the problem? 
Currently i am using:
- Microsoft.CrmSdk.CoreTools version="9.1.0.79"
- spkl version="1.0.633-beta"

**Comment by scottdurow** [comment]
I think is because the solution export/import operations on dataverse are taking a very long time to complete under some circumstances. There has been a slow down on the platform recently that is being addressed.

**Comment by mariokrajmer** [comment]
@scottdurow is this something which will be fixed in some new version of spkl or is this something what microsoft is working on?

**Comment by namurdock** [comment]
@mariokrajmer We had the same thing all afternoon yesterday. This morning the unpack went through. I think its an MS issue rather than SPKL. Using the 1.0.633-beta SPKL package from nuget has helped us a lot.

**Comment by scottdurow** [comment]
Yes - this is a MS issue - nothing we can do apart from retry at the moment.

**Comment by AndersHybridPro** [comment]
I am getting this consistently this week across environments. Retries does not help.
"The underlying connection was closed: The connection was closed unexpectedly."
Using the latest spkl version. For now, I have resorted to download manually, but need to figure something else out, in order to get it into source control.

**Comment by scottdurow** [comment]
Hi @AndersHybridPro  - Which version of spkl and the core tools are you using? Can you ensure you are using 1.0.640 if not already by updating your nuget packages. If this does not help - could you post the entire stack track of the error please.

**Comment by AndersHybridPro** [comment]
> Hi @AndersHybridPro - Which version of spkl and the core tools are you using? Can you ensure you are using 1.0.640 if not already by updating your nuget packages. If this does not help - could you post the entire stack track of the error please.

Hi Scott,
Thanks for your reply! I just got back to work on Monday, and then it worked without an issue on all my clients. So it seems like Microsoft re-fixed something. So nothing wrong with the spkl package :).
