### ISSUE TITLE
NullReferenceException when registering plugin to a CustomApi

### ISSUE THREAD

**Issue by christoph-burker** [scottdurow/SparkleXrm#434]
Deploying Plugins
Searching for plugin config in 'C:\_git\----.Dataverse.CustomApi\spkl\..'
Using Config 'C:\_git\----.Dataverse.CustomApi'
Checking assembly '----.Dataverse.CustomApi.dll' for plugins
1 plugin(s) found!
The application terminated with an error.
Object reference not set to an instance of an object.
   at SparkleXrm.Tasks.Reflection.<>c.<GetAttributes>b__4_2(CrmPluginRegistrationAttribute s)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at SparkleXrm.Tasks.Reflection.GetAttributes(IEnumerable`1 types, String attributeName)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterAssembly(FileInfo assemblyFilePath, Assembly assembly, IEnumerable`1 pluginTypes, Boolean isWorkflowActivity)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterPlugin(String file, Boolean excludePluginSteps)
   at SparkleXrm.Tasks.DeployPluginsTask.DeployPlugins(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.DeployPluginsTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Error Code=1

**Comment by christoph-burker** [comment]
Nevermind, it seems the deploy script chose an old spkl.exe version that was still lying about in the packages folder.
Is it really a good idea to just take the first version the script finds? This seems kind of arbitrary and error-prone.
