### ISSUE TITLE
Object reference not set to an instance of an object when registering a plugin

### ISSUE THREAD

**Issue by AleksandrRogov** [scottdurow/SparkleXrm#440]
spkl version: 1.0.640.

When registering a new plugin  I am getting the following error:

```
The application terminated with an error.
Object reference not set to an instance of an object.
   at SparkleXrm.Tasks.PluginRegistraton.normaliseCommaSeparatedString(String input)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterStep(PluginType sdkPluginType, List`1 existingSteps, CrmPluginRegistrationAttribute pluginStep)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterPluginSteps(IEnumerable`1 pluginTypes, PluginAssembly plugin)
   at SparkleXrm.Tasks.PluginRegistraton.RegisterPlugin(String file, Boolean excludePluginSteps)
   at SparkleXrm.Tasks.DeployPluginsTask.DeployPlugins(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.DeployPluginsTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Error Code=1
```

The plugin assembly gets deployed but it does not have any registered steps, so I think it happens when a new step gets registered.

I've got the following Plugin Registration attribute:

```c#
[CrmPluginRegistration(MessageNameEnum.Create, Incident.EntityLogicalName, StageEnum.PreOperation, ExecutionModeEnum.Synchronous,
	filteringAttributes: null, stepName: "My.Plugins - Create of Case", executionOrder: 1,
	isolationModel: IsolationModeEnum.Sandbox, Id = "6D8F5EEF-072A-4D39-B707-8C0C858550D0"
)]
```

I am guessing the error happens because this [method](https://github.com/scottdurow/SparkleXrm/blob/8853a7556c8827c92810c5805df32b12c1867aa4/spkl/SparkleXrm.Tasks/PluginRegistraton.cs#L589) - it does not have a null check for an `input` parameter, that's the only line in there.

**Comment by OliverFlint** [comment]
Hi @AleksandrRogov 
We have also experienced this ourselves when switching from v1.0.440 to v1.0.640.
For now our fix has been to specify the filtering attributes as "" (empty string)
