### ISSUE TITLE
Nullable object must have a value error

### ISSUE THREAD

**Issue by bwmodular** [scottdurow/SparkleXrm#454]
Hi,
running _instrument-plugin-code.bat_ on an environment which I've not run it against for a long time and I'm getting a 'Nullable object must have a value' error.

spkl v1.0.640
Dynamics 365 online 2022 release wave 1

Here are the logs:
Downloading Plugin/Workflow Activity Metadata
Searching for classes in 'C:\blah\Plugins\spkl\..'
Found Plugin Type Registration blah.Plugins.AccountPlugin
Found Plugin Type Registration blah.Plugins.Account_CreateTMExtractRecord
The application terminated with an error.
Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at SparkleXrm.Tasks.DownloadPluginMetadataTask.AddPluginAttributes(OrganizationServiceContext ctx, CodeParser parser, String pluginType)
   at SparkleXrm.Tasks.DownloadPluginMetadataTask.ExecuteInternal(String filePath, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Error Code=1

I have run _deploy-plugins.bat_ previously and that works ok.

Any ideas what might be causing this?

I can't see any issue with the plugin/step that it seems to be failing on.

Thanks as ever....

**Comment by scottdurow** [comment]
I'll take a look into this!

**Comment by ALRobilliard** [comment]
I can't figure out why, but it's something to do with the Async/Sync mode of the step. I'm getting the same error as @bwmodular when instrumenting async plugins, but it works fine with sync.

To progress I'm: 
1. Converting all my async plugin steps to sync
2. Running _instrument-plugin-code.bat_
3. Updating the generated _CrmPluginRegistration_ back from sync to async
4. Run _deploy-plugins.bat_ to fix all the steps in my environment

**Comment by samalex1701** [comment]
I'm getting the same error. VS 2019 with spkl Task Runner v1.0.640.1.  I've tested both with On Prem CRM v8.2.28.11 and Online v9.2.22071.176 both with same results.  As @ALRobilliard suggested I can change already deployed plugins to Synchronous and the Instrument-plugin-code.bat runs, but being set to Async gives the error.  Thus far I've had mixed results deploying plugins set to Sync or ASync, but it seems to work with the online 9.2 more consistently.  

Downloading Plugin/Workflow Activity Metadata
Searching for classes in 'C:\Users\***\source\repos\****\spkl\..'
Found Plugin Type Registration *****
The application terminated with an error.
Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at SparkleXrm.Tasks.DownloadPluginMetadataTask.AddPluginAttributes(OrganizationServiceContext ctx, CodeParser parser, String pluginType)
   at SparkleXrm.Tasks.DownloadPluginMetadataTask.ExecuteInternal(String filePath, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Error Code=1
