### ISSUE TITLE
Incompatibility with Microsoft.CrmSdk.CoreTools v9.1.0.115

### ISSUE THREAD

**Issue by tylersand** [scottdurow/SparkleXrm#461]
When using the earlybound.bat with the latest Microsoft.CrmSdk.CoreTools v9.1.0.115, it throws an exception regarding "Parameter count mismatch".  Works fine with v9.1.0.79.

Generating early bound types
Searching for plugin config in 'C:\demos\DataversePlugins\spkl\..'
Using Config 'C:\demos\DataversePlugins'
Target C:\demos\DataverseSolution\packages\spkl.1.0.640\tools
Running C:\demos\DataverseSolution\packages\spkl.1.0.640\tools\..\..\Microsoft.CrmSdk.CoreTools.9.1.0.115\content\bin\coretools\CrmSvcUtil.exe /connstr:"AuthType=OAuth;
                      AppId=xxx;
                      RedirectUri=app://xxx;
                      TokenCacheStorePath=C:\Users\tyler\AppData\Roaming\spkl\TokenCache;UserName=xxx;Url=https://xxx.crm.dynamics.com;LoginPrompt=Auto" /out:"C:\demos\DataversePlugins\EarlyBoundTypes.cs" /namespace:"DataversePlugins" /serviceContextName:"XrmSvc" /GenerateActions:"False" /codewriterfilter:"spkl.CrmSvcUtilExtensions.FilteringService,spkl.CrmSvcUtilExtensions" /codewritermessagefilter:"spkl.CrmSvcUtilExtensions.MessageFilteringService,spkl.CrmSvcUtilExtensions" /codegenerationservice:"spkl.CrmSvcUtilExtensions.CodeGenerationService, spkl.CrmSvcUtilExtensions" /metadataproviderqueryservice:"spkl.CrmSvcUtilExtensions.MetadataProviderQueryService,spkl.CrmSvcUtilExtensions"
CrmSvcUtil : CRM Service Utility [Version 9.1.0.118]
c 2022 Microsoft Corporation. All rights reserved

Begin Reading Metadata from MetadataProviderService
Loading config from 'C:\demos\DataverseSolution\packages\Microsoft.CrmSdk.CoreTools.9.1.0.115\content\bin\coretools\spkl.crmsvcutil.config'
        Begin Reading Metadata from Server
        Read 3 Entities
        Read 0 Global OptionSets
        Read 1 SDK Messages
        Completed Reading Metadata from Server - 00:00:08.1054155
Completed Reading Metadata from MetadataProviderService - 00:00:10.3559160

Begin Writing Code File
Exiting program with exception: Parameter count mismatch.
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source    : mscorlib
Method  : InvokeArgumentsCheck
Date    : 11:09:36 AM
Time    : 7/15/2022
Error   : Parameter count mismatch.
Stack Trace     : at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

CrmSvcUtil exited with error 2
Error Code=1

**Comment by PlanBernhard** [comment]
Same issue here. The latest working version of _Microsoft.CrmSdk.CoreTools_ is 9.1.0.92 .

> Exiting program with exception: Parameteranzahlkonflikt.
> CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetParameterCountException: Parameteranzahlkonflikt.
>    bei System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    bei System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    bei spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
>    bei Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
>    bei Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
>    bei Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
> CrmSvcUtil Error: 2 : ===== DETAIL ======
> CrmSvcUtil Error: 2 : Source    : mscorlib
> Method  : InvokeArgumentsCheck
> Date    : 11:49:27
> Time    : 20.07.2022
> Error   : Parameteranzahlkonflikt.
> Stack Trace     : bei System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> culture)
>    bei System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    bei spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
>    bei Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
>    bei Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
>    bei Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
> ======================================================================================================================
> 
> CrmSvcUtil exited with error 2
> Error Code=1

**Comment by PlanBernhard** [comment]
It seems like MS changed some options. Here a comparison of the output of CrmSvcUtil against the latest 
 stable version

![image](https://user-images.githubusercontent.com/86688558/179958273-0baf5e51-8b72-4bc5-a470-e8d6d6ae60f8.png)
![image](https://user-images.githubusercontent.com/86688558/179958810-763f6e2d-81dc-4119-8b9c-1f7b283e29e3.png)

**Comment by PlanBernhard** [comment]
The same for the CrmSvcUtil.xml
![image](https://user-images.githubusercontent.com/86688558/179961282-cc668f10-4b12-4773-8c5c-ce79a9d23d59.png)
![image](https://user-images.githubusercontent.com/86688558/179961347-29a40d9f-e044-49cf-857b-aff2761011ec.png)
![image](https://user-images.githubusercontent.com/86688558/179961393-4c33e7e6-4c75-48bc-ae6d-9d3af5d16f15.png)
![image](https://user-images.githubusercontent.com/86688558/179961504-bfef2291-2992-448c-a6f9-fb07125cfa93.png)
![image](https://user-images.githubusercontent.com/86688558/179961563-8a6222de-77a2-436a-a269-de03ef651e93.png)

**Comment by scottdurow** [comment]
Thanks all - it'll mean the next version of spkl will require the latest SDK core tools.
For now -the workaround is to stay on the older version.

**Comment by PlanBernhard** [comment]
Thanks Scott
