### ISSUE TITLE
 Parameter count mismatch

### ISSUE THREAD

**Issue by Atili0** [scottdurow/SparkleXrm#470]
Hi teams, 

Somebody know something about this error?

12:35:01	CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetParameterCountException: Parameter count mismatch.
12:35:01	   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
12:35:01	   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
12:35:01	CrmSvcUtil Error: 2 : ===== DETAIL ======
12:35:01	CrmSvcUtil Error: 2 : Source	: mscorlib
12:35:01	Method	: InvokeArgumentsCheck
12:35:01	Date	: 12:35:01
12:35:01	Time	: 03/03/2023
12:35:01	Error	: Parameter count mismatch.
12:35:01	Stack Trace	: at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
12:35:01	   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
12:35:01	======================================================================================================================
12:35:01

**Comment by scottdurow** [comment]
Hi @Atili0 - you will need to use version 9.1.0.79 of the core tools instead of the latest - see #461

**Comment by Atili0** [comment]
Hi Scott

thanks for your reply. I downloaded the version 9.1.0.115 but I still having an error 

12:35:01	CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetParameterCountException: Parameter count mismatch.
12:35:01	   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
12:35:01	   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
12:35:01	CrmSvcUtil Error: 2 : ===== DETAIL ======
12:35:01	CrmSvcUtil Error: 2 : Source	: mscorlib
12:35:01	Method	: InvokeArgumentsCheck
12:35:01	Date	: 12:35:01
12:35:01	Time	: 03/03/2023
12:35:01	Error	: Parameter count mismatch.
12:35:01	Stack Trace	: at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:35:01	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
12:35:01	   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
12:35:01	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
12:35:01	======================================================================================================================
12:35:01	
23:53:20		Read 0 Global OptionSets
23:53:20		Read 1 SDK Messages
23:53:20		Completed Reading Metadata from Server - 00:00:13.7266329
23:53:20	Completed Reading Metadata from MetadataProviderService - 00:00:16.5206290
23:53:20	Begin Writing Code File
