### ISSUE TITLE
error when deploy-webresources.bat Access to the path is denied

### ISSUE THREAD

**Issue by siuchon** [scottdurow/SparkleXrm#477]
The application terminated with an error.
Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at SparkleXrm.Tasks.TraceLogger.WriteLine(String format, Object[] args)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Error Code=1

**Comment by siuchon** [comment]
it's because protected folder access blocked by Windows defender
